### ISSUE TITLE
License of project

### ISSUE THREAD

**Issue by Cellesti** [faldor20/jj_tui#5]
Hi, i am the maintainer of the Jujutsu package in Alpine Linux, and have recently come across this interesting project (happy to see that it's written in OCaml :)).

I would like to add a `jj_tui` package to Alpine Linux, but i couldn't find what license it is released under. Grepping for "license" in the source tree only tells me the licenses of the dependencies contained in the `forks` directory.

So, may i know what license this project uses?

Thanks.

**Comment by faldor20** [comment]
There you go, I added a license. Thanks for making it available on alpine!
I'm happy to put a description on how to install for alpine in the readme.

Hope you enjoy the tool.
